# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=1.0.1.8
last_mod_version=1.0.1.7
group=com.github.wendall911.mobchampions

# Common
minecraft_version=1.21.11
mixin_extras_version=0.3.5
whitenoise_version=2.0.7
whitenoise_range=[2.0.0,3.0.0)
fabric_whitenoise_range=[">=2.0.0","<=3.0.0"]
mixin_version=0.8.5
java_version=21

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.37-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.11, 1.21.12)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.141.2+1.21.11
fabric_loader_version=0.18.4
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">=1.21.11","<=1.21.12"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=17.0.0-beta.2

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=7.3.0
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all
jade_neoforge_version=7313008
jade_fabric_version=7312559

# Mod options
mod_display_name=Mob Champions
mod_name=MobChampions
mod_id=mobchampions
mod_author=wendall911
mod_credits=Knoface
license=MIT
mod_description=Mob champions are special elite versions of regular mobs that spawn with armor, weapons, enhanced stats and effects. Legendary loot!
mod_update_branch=1.21

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=mccurseApiKey
curseforge_id=1144299
curseforge_slug=mobchampions
modrinth_api_key_prop=modrinthKey
modrinth_id=zrbKKaSr
discord_webhook_prop=mcDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.11
